# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strichliste', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='double_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strichliste.Transaction'),
        ),
    ]
